-- Run this once in the Supabase SQL editor (Project > SQL Editor > New query)

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  category text not null,
  title text not null,
  desc text not null,
  long_desc text not null,
  duration text not null,
  lessons text not null,
  level text not null,
  language text not null,
  files text not null,
  last_update text not null,
  rating text not null,
  reviews_count text not null,
  students text not null,
  price text not null,
  old_price text not null,
  img text not null,
  modules jsonb not null default '[]'::jsonb,
  reviews jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.courses enable row level security;

create policy "Public read access" on public.courses
  for select using (true);

-- Seed data: the 9 courses already on the site

insert into public.courses (slug, category, title, desc, long_desc, duration, lessons, level, language, files, last_update, rating, reviews_count, students, price, old_price, img, modules, reviews) values
('clat-pg-crash-course', 'CLAT PG', 'CLAT PG Crash Course',
 'Structured prep with mock tests, mentor reviews, and NLU-focused strategy.',
 'This crash course introduces you to a complete CLAT PG preparation strategy through clear explanations, real case studies, and hands-on mock tests. By the end of the program, you''ll understand the exam pattern deeply and be able to approach every section with a clear strategy.',
 '20 hours', '25 Lessons', 'Intermediate', 'English', '20 files', '12 Nov 25', '5.0', '160 reviews', '560', '89.99', '109.99', '/democoursestlp.png',
 '[{"title":"Module 1: Introduction to CLAT PG","items":["What is CLAT PG?","Why it matters for your legal career","Key terms and foundational concepts","How this module connects to the rest of the program"]},{"title":"Module 2: Core Concepts & Frameworks","items":["Breaking down the core principles","Common mistakes students make","Mentor-curated frameworks for faster recall"]},{"title":"Module 3: Practical Application","items":["Worked examples from real cases","Guided practice exercises","Building your own notes and shortcuts"]},{"title":"Module 4: Case Studies & Mock Tests","items":["Timed mock tests with analysis","Reviewing landmark case studies","Identifying and fixing weak areas"]},{"title":"Module 5: Mentor Review & Feedback","items":["One-on-one mentor feedback session","Personalised improvement plan","Q&A with practicing advocates"]},{"title":"Module 6: Final Assessment & Certification","items":["Comprehensive final assessment","Detailed performance report","Certificate of completion"]}]'::jsonb,
 '[{"name":"Jhon Macklonar","role":"CLAT PG Admit @ NLU Delhi","text":"This program completely changed how I understand legal reasoning. The mentor broke down even the most complex topics into simple, digestible lessons. The hands-on exercises helped me finally connect theory with practical drafting.","rating":5,"img":"https://picsum.photos/seed/review1/64/64"},{"name":"Mr Rick","role":"Litigation Intern @ Delhi High Court","text":"This program reshaped the way I think about legal practice. Topics that once felt intimidating were explained in a clear, step-by-step way. The mock tests made everything click and helped me apply what I learned with confidence.","rating":5,"img":"https://picsum.photos/seed/review2/64/64"},{"name":"Nathan Kelly","role":"Legal Intern @ Trilegal","text":"I never thought I''d grasp advanced legal concepts this easily. The mentor''s teaching style made difficult subjects feel approachable, and the real-world case studies kept everything relevant and practical.","rating":5,"img":"https://picsum.photos/seed/review3/64/64"}]'::jsonb
),
('internship-readiness-program', 'Internships', 'Internship Readiness Program',
 'Resume building, mock interviews, and outreach to land litigation internships.',
 'Designed for students struggling to land their first legal internship, this program walks you through resume building, cold outreach, and mock interviews so you walk into every opportunity prepared and confident.',
 '15 hours', '18 Lessons', 'Beginner', 'English', '16 files', '08 Nov 25', '4.9', '98 reviews', '410', '69.99', '89.99', 'https://picsum.photos/seed/catalog2/480/320',
 '[{"title":"Module 1: Introduction to Internship Outreach","items":["What is Internship Outreach?","Why it matters for your legal career","Key terms and foundational concepts","How this module connects to the rest of the program"]},{"title":"Module 2: Core Concepts & Frameworks","items":["Breaking down the core principles","Common mistakes students make","Mentor-curated frameworks for faster recall"]},{"title":"Module 3: Practical Application","items":["Worked examples from real cases","Guided practice exercises","Building your own notes and shortcuts"]},{"title":"Module 4: Case Studies & Mock Tests","items":["Timed mock tests with analysis","Reviewing landmark case studies","Identifying and fixing weak areas"]},{"title":"Module 5: Mentor Review & Feedback","items":["One-on-one mentor feedback session","Personalised improvement plan","Q&A with practicing advocates"]},{"title":"Module 6: Final Assessment & Certification","items":["Comprehensive final assessment","Detailed performance report","Certificate of completion"]}]'::jsonb,
 '[{"name":"Jhon Macklonar","role":"CLAT PG Admit @ NLU Delhi","text":"This program completely changed how I understand legal reasoning. The mentor broke down even the most complex topics into simple, digestible lessons. The hands-on exercises helped me finally connect theory with practical drafting.","rating":5,"img":"https://picsum.photos/seed/review1/64/64"},{"name":"Mr Rick","role":"Litigation Intern @ Delhi High Court","text":"This program reshaped the way I think about legal practice. Topics that once felt intimidating were explained in a clear, step-by-step way. The mock tests made everything click and helped me apply what I learned with confidence.","rating":5,"img":"https://picsum.photos/seed/review2/64/64"},{"name":"Nathan Kelly","role":"Legal Intern @ Trilegal","text":"I never thought I''d grasp advanced legal concepts this easily. The mentor''s teaching style made difficult subjects feel approachable, and the real-world case studies kept everything relevant and practical.","rating":5,"img":"https://picsum.photos/seed/review3/64/64"}]'::jsonb
),
('legal-drafting-contract-skills', 'Drafting', 'Legal Drafting & Contract Skills',
 'Hands-on drafting practice for contracts, pleadings, and legal notices.',
 'Move beyond theory and get hands-on with this practical drafting course covering contracts, pleadings, and legal notices, taught the practical way employers and chambers actually expect.',
 '18 hours', '22 Lessons', 'Intermediate', 'English', '20 files', '02 Nov 25', '4.9', '142 reviews', '620', '99.99', '129.99', 'https://picsum.photos/seed/catalog3/480/320',
 '[{"title":"Module 1: Introduction to Legal Drafting","items":["What is Legal Drafting?","Why it matters for your legal career","Key terms and foundational concepts","How this module connects to the rest of the program"]},{"title":"Module 2: Core Concepts & Frameworks","items":["Breaking down the core principles","Common mistakes students make","Mentor-curated frameworks for faster recall"]},{"title":"Module 3: Practical Application","items":["Worked examples from real cases","Guided practice exercises","Building your own notes and shortcuts"]},{"title":"Module 4: Case Studies & Mock Tests","items":["Timed mock tests with analysis","Reviewing landmark case studies","Identifying and fixing weak areas"]},{"title":"Module 5: Mentor Review & Feedback","items":["One-on-one mentor feedback session","Personalised improvement plan","Q&A with practicing advocates"]},{"title":"Module 6: Final Assessment & Certification","items":["Comprehensive final assessment","Detailed performance report","Certificate of completion"]}]'::jsonb,
 '[{"name":"Jhon Macklonar","role":"CLAT PG Admit @ NLU Delhi","text":"This program completely changed how I understand legal reasoning. The mentor broke down even the most complex topics into simple, digestible lessons. The hands-on exercises helped me finally connect theory with practical drafting.","rating":5,"img":"https://picsum.photos/seed/review1/64/64"},{"name":"Mr Rick","role":"Litigation Intern @ Delhi High Court","text":"This program reshaped the way I think about legal practice. Topics that once felt intimidating were explained in a clear, step-by-step way. The mock tests made everything click and helped me apply what I learned with confidence.","rating":5,"img":"https://picsum.photos/seed/review2/64/64"},{"name":"Nathan Kelly","role":"Legal Intern @ Trilegal","text":"I never thought I''d grasp advanced legal concepts this easily. The mentor''s teaching style made difficult subjects feel approachable, and the real-world case studies kept everything relevant and practical.","rating":5,"img":"https://picsum.photos/seed/review3/64/64"}]'::jsonb
),
('moot-court-advocacy-mastery', 'Moot Court', 'Moot Court & Advocacy Mastery',
 'Build courtroom presence with live moot sessions and mentor feedback.',
 'Build real courtroom presence through live moot court sessions, judged rounds, and detailed mentor feedback designed to sharpen your advocacy and oral argument skills.',
 '22 hours', '20 Lessons', 'Advanced', 'English', '18 files', '28 Oct 25', '4.8', '76 reviews', '290', '79.99', '99.99', 'https://picsum.photos/seed/catalog4/480/320',
 '[{"title":"Module 1: Introduction to Advocacy","items":["What is Advocacy?","Why it matters for your legal career","Key terms and foundational concepts","How this module connects to the rest of the program"]},{"title":"Module 2: Core Concepts & Frameworks","items":["Breaking down the core principles","Common mistakes students make","Mentor-curated frameworks for faster recall"]},{"title":"Module 3: Practical Application","items":["Worked examples from real cases","Guided practice exercises","Building your own notes and shortcuts"]},{"title":"Module 4: Case Studies & Mock Tests","items":["Timed mock tests with analysis","Reviewing landmark case studies","Identifying and fixing weak areas"]},{"title":"Module 5: Mentor Review & Feedback","items":["One-on-one mentor feedback session","Personalised improvement plan","Q&A with practicing advocates"]},{"title":"Module 6: Final Assessment & Certification","items":["Comprehensive final assessment","Detailed performance report","Certificate of completion"]}]'::jsonb,
 '[{"name":"Jhon Macklonar","role":"CLAT PG Admit @ NLU Delhi","text":"This program completely changed how I understand legal reasoning. The mentor broke down even the most complex topics into simple, digestible lessons. The hands-on exercises helped me finally connect theory with practical drafting.","rating":5,"img":"https://picsum.photos/seed/review1/64/64"},{"name":"Mr Rick","role":"Litigation Intern @ Delhi High Court","text":"This program reshaped the way I think about legal practice. Topics that once felt intimidating were explained in a clear, step-by-step way. The mock tests made everything click and helped me apply what I learned with confidence.","rating":5,"img":"https://picsum.photos/seed/review2/64/64"},{"name":"Nathan Kelly","role":"Legal Intern @ Trilegal","text":"I never thought I''d grasp advanced legal concepts this easily. The mentor''s teaching style made difficult subjects feel approachable, and the real-world case studies kept everything relevant and practical.","rating":5,"img":"https://picsum.photos/seed/review3/64/64"}]'::jsonb
),
('corporate-law-fundamentals', 'Corporate Law', 'Corporate Law Fundamentals',
 'Understand M&A, compliance, and corporate structuring from practicing counsel.',
 'Understand the building blocks of corporate practice — M&A, compliance, and corporate structuring — taught by mentors with real in-house and law firm experience.',
 '20 hours', '24 Lessons', 'Intermediate', 'English', '19 files', '20 Oct 25', '4.8', '88 reviews', '350', '94.99', '119.99', 'https://picsum.photos/seed/catalog5/480/320',
 '[{"title":"Module 1: Introduction to Corporate Law","items":["What is Corporate Law?","Why it matters for your legal career","Key terms and foundational concepts","How this module connects to the rest of the program"]},{"title":"Module 2: Core Concepts & Frameworks","items":["Breaking down the core principles","Common mistakes students make","Mentor-curated frameworks for faster recall"]},{"title":"Module 3: Practical Application","items":["Worked examples from real cases","Guided practice exercises","Building your own notes and shortcuts"]},{"title":"Module 4: Case Studies & Mock Tests","items":["Timed mock tests with analysis","Reviewing landmark case studies","Identifying and fixing weak areas"]},{"title":"Module 5: Mentor Review & Feedback","items":["One-on-one mentor feedback session","Personalised improvement plan","Q&A with practicing advocates"]},{"title":"Module 6: Final Assessment & Certification","items":["Comprehensive final assessment","Detailed performance report","Certificate of completion"]}]'::jsonb,
 '[{"name":"Jhon Macklonar","role":"CLAT PG Admit @ NLU Delhi","text":"This program completely changed how I understand legal reasoning. The mentor broke down even the most complex topics into simple, digestible lessons. The hands-on exercises helped me finally connect theory with practical drafting.","rating":5,"img":"https://picsum.photos/seed/review1/64/64"},{"name":"Mr Rick","role":"Litigation Intern @ Delhi High Court","text":"This program reshaped the way I think about legal practice. Topics that once felt intimidating were explained in a clear, step-by-step way. The mock tests made everything click and helped me apply what I learned with confidence.","rating":5,"img":"https://picsum.photos/seed/review2/64/64"},{"name":"Nathan Kelly","role":"Legal Intern @ Trilegal","text":"I never thought I''d grasp advanced legal concepts this easily. The mentor''s teaching style made difficult subjects feel approachable, and the real-world case studies kept everything relevant and practical.","rating":5,"img":"https://picsum.photos/seed/review3/64/64"}]'::jsonb
),
('legal-research-case-analysis', 'CLAT PG', 'Legal Research & Case Analysis',
 'Master case law research, citation, and analytical writing.',
 'Master the art of legal research, citation, and analytical writing used by top litigators — a foundational skill for every successful legal career.',
 '16 hours', '19 Lessons', 'Beginner', 'English', '14 files', '15 Oct 25', '4.9', '120 reviews', '480', '59.99', '79.99', 'https://picsum.photos/seed/catalog6/480/320',
 '[{"title":"Module 1: Introduction to Legal Research","items":["What is Legal Research?","Why it matters for your legal career","Key terms and foundational concepts","How this module connects to the rest of the program"]},{"title":"Module 2: Core Concepts & Frameworks","items":["Breaking down the core principles","Common mistakes students make","Mentor-curated frameworks for faster recall"]},{"title":"Module 3: Practical Application","items":["Worked examples from real cases","Guided practice exercises","Building your own notes and shortcuts"]},{"title":"Module 4: Case Studies & Mock Tests","items":["Timed mock tests with analysis","Reviewing landmark case studies","Identifying and fixing weak areas"]},{"title":"Module 5: Mentor Review & Feedback","items":["One-on-one mentor feedback session","Personalised improvement plan","Q&A with practicing advocates"]},{"title":"Module 6: Final Assessment & Certification","items":["Comprehensive final assessment","Detailed performance report","Certificate of completion"]}]'::jsonb,
 '[{"name":"Jhon Macklonar","role":"CLAT PG Admit @ NLU Delhi","text":"This program completely changed how I understand legal reasoning. The mentor broke down even the most complex topics into simple, digestible lessons. The hands-on exercises helped me finally connect theory with practical drafting.","rating":5,"img":"https://picsum.photos/seed/review1/64/64"},{"name":"Mr Rick","role":"Litigation Intern @ Delhi High Court","text":"This program reshaped the way I think about legal practice. Topics that once felt intimidating were explained in a clear, step-by-step way. The mock tests made everything click and helped me apply what I learned with confidence.","rating":5,"img":"https://picsum.photos/seed/review2/64/64"},{"name":"Nathan Kelly","role":"Legal Intern @ Trilegal","text":"I never thought I''d grasp advanced legal concepts this easily. The mentor''s teaching style made difficult subjects feel approachable, and the real-world case studies kept everything relevant and practical.","rating":5,"img":"https://picsum.photos/seed/review3/64/64"}]'::jsonb
),
('constitutional-law-deep-dive', 'CLAT PG', 'Constitutional Law Deep Dive',
 'Go beyond the basics with landmark judgments and applied reasoning.',
 'Go beyond the basics of constitutional law with an in-depth study of landmark judgments and the applied reasoning examiners and interviewers actually look for.',
 '17 hours', '21 Lessons', 'Advanced', 'English', '17 files', '10 Oct 25', '4.7', '64 reviews', '260', '74.99', '94.99', 'https://picsum.photos/seed/catalog7/480/320',
 '[{"title":"Module 1: Introduction to Constitutional Law","items":["What is Constitutional Law?","Why it matters for your legal career","Key terms and foundational concepts","How this module connects to the rest of the program"]},{"title":"Module 2: Core Concepts & Frameworks","items":["Breaking down the core principles","Common mistakes students make","Mentor-curated frameworks for faster recall"]},{"title":"Module 3: Practical Application","items":["Worked examples from real cases","Guided practice exercises","Building your own notes and shortcuts"]},{"title":"Module 4: Case Studies & Mock Tests","items":["Timed mock tests with analysis","Reviewing landmark case studies","Identifying and fixing weak areas"]},{"title":"Module 5: Mentor Review & Feedback","items":["One-on-one mentor feedback session","Personalised improvement plan","Q&A with practicing advocates"]},{"title":"Module 6: Final Assessment & Certification","items":["Comprehensive final assessment","Detailed performance report","Certificate of completion"]}]'::jsonb,
 '[{"name":"Jhon Macklonar","role":"CLAT PG Admit @ NLU Delhi","text":"This program completely changed how I understand legal reasoning. The mentor broke down even the most complex topics into simple, digestible lessons. The hands-on exercises helped me finally connect theory with practical drafting.","rating":5,"img":"https://picsum.photos/seed/review1/64/64"},{"name":"Mr Rick","role":"Litigation Intern @ Delhi High Court","text":"This program reshaped the way I think about legal practice. Topics that once felt intimidating were explained in a clear, step-by-step way. The mock tests made everything click and helped me apply what I learned with confidence.","rating":5,"img":"https://picsum.photos/seed/review2/64/64"},{"name":"Nathan Kelly","role":"Legal Intern @ Trilegal","text":"I never thought I''d grasp advanced legal concepts this easily. The mentor''s teaching style made difficult subjects feel approachable, and the real-world case studies kept everything relevant and practical.","rating":5,"img":"https://picsum.photos/seed/review3/64/64"}]'::jsonb
),
('judiciary-exam-preparation', 'CLAT PG', 'Judiciary Exam Preparation',
 'A complete roadmap for state judicial services examinations.',
 'A complete, mentor-guided roadmap for state judicial services examinations — from prelims strategy to mains answer-writing and interview preparation.',
 '25 hours', '28 Lessons', 'Advanced', 'English', '24 files', '05 Oct 25', '4.8', '102 reviews', '390', '109.99', '139.99', 'https://picsum.photos/seed/catalog8/480/320',
 '[{"title":"Module 1: Introduction to Judicial Services","items":["What is Judicial Services?","Why it matters for your legal career","Key terms and foundational concepts","How this module connects to the rest of the program"]},{"title":"Module 2: Core Concepts & Frameworks","items":["Breaking down the core principles","Common mistakes students make","Mentor-curated frameworks for faster recall"]},{"title":"Module 3: Practical Application","items":["Worked examples from real cases","Guided practice exercises","Building your own notes and shortcuts"]},{"title":"Module 4: Case Studies & Mock Tests","items":["Timed mock tests with analysis","Reviewing landmark case studies","Identifying and fixing weak areas"]},{"title":"Module 5: Mentor Review & Feedback","items":["One-on-one mentor feedback session","Personalised improvement plan","Q&A with practicing advocates"]},{"title":"Module 6: Final Assessment & Certification","items":["Comprehensive final assessment","Detailed performance report","Certificate of completion"]}]'::jsonb,
 '[{"name":"Jhon Macklonar","role":"CLAT PG Admit @ NLU Delhi","text":"This program completely changed how I understand legal reasoning. The mentor broke down even the most complex topics into simple, digestible lessons. The hands-on exercises helped me finally connect theory with practical drafting.","rating":5,"img":"https://picsum.photos/seed/review1/64/64"},{"name":"Mr Rick","role":"Litigation Intern @ Delhi High Court","text":"This program reshaped the way I think about legal practice. Topics that once felt intimidating were explained in a clear, step-by-step way. The mock tests made everything click and helped me apply what I learned with confidence.","rating":5,"img":"https://picsum.photos/seed/review2/64/64"},{"name":"Nathan Kelly","role":"Legal Intern @ Trilegal","text":"I never thought I''d grasp advanced legal concepts this easily. The mentor''s teaching style made difficult subjects feel approachable, and the real-world case studies kept everything relevant and practical.","rating":5,"img":"https://picsum.photos/seed/review3/64/64"}]'::jsonb
),
('contract-drafting-for-beginners', 'Drafting', 'Contract Drafting for Beginners',
 'Start from scratch and build confidence drafting everyday legal documents.',
 'Start from scratch and build real confidence drafting everyday legal documents — from simple agreements to notices — with guided templates and mentor review.',
 '12 hours', '15 Lessons', 'Beginner', 'English', '12 files', '01 Oct 25', '4.6', '54 reviews', '210', '54.99', '69.99', 'https://picsum.photos/seed/catalog9/480/320',
 '[{"title":"Module 1: Introduction to Contract Drafting","items":["What is Contract Drafting?","Why it matters for your legal career","Key terms and foundational concepts","How this module connects to the rest of the program"]},{"title":"Module 2: Core Concepts & Frameworks","items":["Breaking down the core principles","Common mistakes students make","Mentor-curated frameworks for faster recall"]},{"title":"Module 3: Practical Application","items":["Worked examples from real cases","Guided practice exercises","Building your own notes and shortcuts"]},{"title":"Module 4: Case Studies & Mock Tests","items":["Timed mock tests with analysis","Reviewing landmark case studies","Identifying and fixing weak areas"]},{"title":"Module 5: Mentor Review & Feedback","items":["One-on-one mentor feedback session","Personalised improvement plan","Q&A with practicing advocates"]},{"title":"Module 6: Final Assessment & Certification","items":["Comprehensive final assessment","Detailed performance report","Certificate of completion"]}]'::jsonb,
 '[{"name":"Jhon Macklonar","role":"CLAT PG Admit @ NLU Delhi","text":"This program completely changed how I understand legal reasoning. The mentor broke down even the most complex topics into simple, digestible lessons. The hands-on exercises helped me finally connect theory with practical drafting.","rating":5,"img":"https://picsum.photos/seed/review1/64/64"},{"name":"Mr Rick","role":"Litigation Intern @ Delhi High Court","text":"This program reshaped the way I think about legal practice. Topics that once felt intimidating were explained in a clear, step-by-step way. The mock tests made everything click and helped me apply what I learned with confidence.","rating":5,"img":"https://picsum.photos/seed/review2/64/64"},{"name":"Nathan Kelly","role":"Legal Intern @ Trilegal","text":"I never thought I''d grasp advanced legal concepts this easily. The mentor''s teaching style made difficult subjects feel approachable, and the real-world case studies kept everything relevant and practical.","rating":5,"img":"https://picsum.photos/seed/review3/64/64"}]'::jsonb
);
